const { contextBridge, ipcRenderer } = require("electron");

// This file runs in a special sandbox between Node and the browser.
// It exposes a safe, limited API to your React code via window.electronAPI.

function subscribe(channel, callback) {
  const handler = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld("electronAPI", {
  system: {
    openDirectory: () => ipcRenderer.invoke("system:openDirectory"),
    openExternal: (url) => ipcRenderer.invoke("system:openExternal", url),
    getCommonPaths: () => ipcRenderer.invoke("system:getCommonPaths"),
    getBuildTag: () => ipcRenderer.invoke("system:getBuildTag"),
    platform: process.platform,
  },

  process: {
    run: (payload) => ipcRenderer.invoke("process:run", payload),
    cancel: (processId) => ipcRenderer.invoke("process:cancel", processId),
    listRunning: () => ipcRenderer.invoke("process:listRunning"),
    onStarted: (callback) => subscribe("process:started", callback),
    onOutput: (callback) => subscribe("process:output", callback),
    onCompleted: (callback) => subscribe("process:completed", callback),
    onError: (callback) => subscribe("process:error", callback),
    onCancelled: (callback) => subscribe("process:cancelled", callback),
    onTimeout: (callback) => subscribe("process:timeout", callback),
  },

  repo: {
    inspect: (repoPath) => ipcRenderer.invoke("repo:inspect", repoPath),
    listDirectory: (targetPath) => ipcRenderer.invoke("repo:listDirectory", targetPath),
    readFileContent: (targetPath) => ipcRenderer.invoke("repo:readFileContent", targetPath),
    writeFileContent: (payload) => ipcRenderer.invoke("repo:writeFileContent", payload),
    getFileDiff: (payload) => ipcRenderer.invoke("repo:getFileDiff", payload),
    stageFiles: (payload) => ipcRenderer.invoke("repo:stageFiles", payload),
    unstageFiles: (payload) => ipcRenderer.invoke("repo:unstageFiles", payload),
    commit: (payload) => ipcRenderer.invoke("repo:commit", payload),
    checkoutBranch: (payload) => ipcRenderer.invoke("repo:checkoutBranch", payload),
    getCommitDetails: (payload) => ipcRenderer.invoke("repo:getCommitDetails", payload),
    getRemoteUrl: (repoPath) => ipcRenderer.invoke("repo:getRemoteUrl", repoPath),
    push: (payload) => ipcRenderer.invoke("repo:push", payload),
    pull: (payload) => ipcRenderer.invoke("repo:pull", payload),
    syncSharedState: (payload) => ipcRenderer.invoke("repo:syncSharedState", payload),
  },

  settings: {
    get: () => ipcRenderer.invoke("settings:get"),
    update: (patch) => ipcRenderer.invoke("settings:update", patch),
    isFirstRun: () => ipcRenderer.invoke("settings:isFirstRun"),
    completeOnboarding: () => ipcRenderer.invoke("settings:completeOnboarding"),
    onChanged: (callback) => subscribe("settings:changed", callback),
  },

  project: {
    list: () => ipcRenderer.invoke("project:list"),
    create: (payload) => ipcRenderer.invoke("project:create", payload),
    delete: (payload) => ipcRenderer.invoke("project:delete", payload),
    grantDeleteScope: () => ipcRenderer.invoke("project:grantDeleteScope"),
    setActive: (projectId) => ipcRenderer.invoke("project:setActive", projectId),
    importSyncedPlan: (projectId) => ipcRenderer.invoke("project:importSyncedPlan", projectId),
    syncWorkspace: (projectId) => ipcRenderer.invoke("project:syncWorkspace", projectId),
    savePlan: (payload) => ipcRenderer.invoke("project:savePlan", payload),
    generatePlan: (payload) => ipcRenderer.invoke("project:generatePlan", payload),
    ensureGithubRepo: (projectId) => ipcRenderer.invoke("project:ensureGithubRepo", projectId),
    listCollaborators: (repoPath) => ipcRenderer.invoke("project:listCollaborators", repoPath),
    setRepoVisibility: (payload) => ipcRenderer.invoke("project:setRepoVisibility", payload),
    sendTaskMessage: (payload) => ipcRenderer.invoke("project:sendTaskMessage", payload),
    generateTaskPrompt: (payload) => ipcRenderer.invoke("project:generateTaskPrompt", payload),
    sendPMMessage: (payload) => ipcRenderer.invoke("project:sendPMMessage", payload),
    sendSoloMessage: (payload) => ipcRenderer.invoke("project:sendSoloMessage", payload),
    cancelActiveRequest: () => ipcRenderer.invoke("project:cancelActiveRequest"),
    forceResetAgent: (payload) => ipcRenderer.invoke("project:forceResetAgent", payload),
    getActiveRequest: () => ipcRenderer.invoke("project:getActiveRequest"),
    launchDevServer: (payload) => ipcRenderer.invoke("project:launchDevServer", payload),
    restoreCheckpoint: (payload) => ipcRenderer.invoke("project:restoreCheckpoint", payload),
    onAgentStarted: (callback) => subscribe("project:agentStarted", callback),
    onAgentOutput: (callback) => subscribe("project:agentOutput", callback),
    onAgentCompleted: (callback) => subscribe("project:agentCompleted", callback),
    onAgentError: (callback) => subscribe("project:agentError", callback),
    onAgentCancelled: (callback) => subscribe("project:agentCancelled", callback),
  },

  tools: {
    listStatus: () => ipcRenderer.invoke("tools:listStatus"),
    getModelCatalogs: () => ipcRenderer.invoke("tools:getModelCatalogs"),
    installCopilot: () => ipcRenderer.invoke("tools:installCopilot"),
    installClaude: () => ipcRenderer.invoke("tools:installClaude"),
    installNode: () => ipcRenderer.invoke("tools:installNode"),
    installGit: () => ipcRenderer.invoke("tools:installGit"),
    installGh: () => ipcRenderer.invoke("tools:installGh"),
    installPython: () => ipcRenderer.invoke("tools:installPython"),
    installCodex: () => ipcRenderer.invoke("tools:installCodex"),
    setupGit: () => ipcRenderer.invoke("tools:setupGit"),
    runCopilotPrompt: (payload) => ipcRenderer.invoke("tools:runCopilotPrompt", payload),
    runGenericPrompt: (payload) => ipcRenderer.invoke("tools:runGenericPrompt", payload),
    githubAuthStatus: () => ipcRenderer.invoke("tools:githubAuthStatus"),
    githubAuthLogin: () => ipcRenderer.invoke("tools:githubAuthLogin"),
    githubAuthLogout: (username) => ipcRenderer.invoke("tools:githubAuthLogout", username),
    onGithubAuthProgress: (callback) => subscribe("tools:githubAuthProgress", callback),
    githubListAccounts: () => ipcRenderer.invoke("tools:githubListAccounts"),
    githubSwitchAccount: (username) => ipcRenderer.invoke("tools:githubSwitchAccount", username),
    claudeAuthStatus: () => ipcRenderer.invoke("tools:claudeAuthStatus"),
    claudeAuthLogin: () => ipcRenderer.invoke("tools:claudeAuthLogin"),
    onClaudeAuthProgress: (callback) => subscribe("tools:claudeAuthProgress", callback),
    codexAuthStatus: () => ipcRenderer.invoke("tools:codexAuthStatus"),
    codexAuthLogin: () => ipcRenderer.invoke("tools:codexAuthLogin"),
    onCodexAuthProgress: (callback) => subscribe("tools:codexAuthProgress", callback),
  },

  sharedState: {
    init: (repoPath) => ipcRenderer.invoke("sharedState:init", repoPath),
    isInitialized: (repoPath) => ipcRenderer.invoke("sharedState:isInitialized", repoPath),
    readFile: (payload) => ipcRenderer.invoke("sharedState:readFile", payload),
    writeFile: (payload) => ipcRenderer.invoke("sharedState:writeFile", payload),
    listDir: (payload) => ipcRenderer.invoke("sharedState:listDir", payload),
    saveConversation: (payload) => ipcRenderer.invoke("sharedState:saveConversation", payload),
    loadConversation: (payload) => ipcRenderer.invoke("sharedState:loadConversation", payload),
    listConversations: (repoPath) => ipcRenderer.invoke("sharedState:listConversations", repoPath),
    saveMember: (payload) => ipcRenderer.invoke("sharedState:saveMember", payload),
    listMembers: (repoPath) => ipcRenderer.invoke("sharedState:listMembers", repoPath),
  },

  p2p: {
    join: (payload) => ipcRenderer.invoke("p2p:join", payload),
    leave: (payload) => ipcRenderer.invoke("p2p:leave", payload),
    status: (payload) => ipcRenderer.invoke("p2p:status", payload),
    peers: (payload) => ipcRenderer.invoke("p2p:peers", payload),
    joinedProjects: () => ipcRenderer.invoke("p2p:joinedProjects"),
    broadcastChatToken: (payload) => ipcRenderer.invoke("p2p:broadcastChatToken", payload),
    broadcastChatMessage: (payload) => ipcRenderer.invoke("p2p:broadcastChatMessage", payload),
    broadcastStateChange: (payload) => ipcRenderer.invoke("p2p:broadcastStateChange", payload),
    getActivePeerStreams: (payload) => ipcRenderer.invoke("p2p:getActivePeerStreams", payload),
    generateInvite: (payload) => ipcRenderer.invoke("p2p:generateInvite", payload),
    decodeInvite: (payload) => ipcRenderer.invoke("p2p:decodeInvite", payload),
    acceptInvite: (payload) => ipcRenderer.invoke("p2p:acceptInvite", payload),
    onJoined: (callback) => subscribe("p2p:joined", callback),
    onLeft: (callback) => subscribe("p2p:left", callback),
    onPeerJoined: (callback) => subscribe("p2p:peerJoined", callback),
    onPeerLeft: (callback) => subscribe("p2p:peerLeft", callback),
    onPresence: (callback) => subscribe("p2p:presence", callback),
    onChatToken: (callback) => subscribe("p2p:chatToken", callback),
    onChatMessage: (callback) => subscribe("p2p:chatMessage", callback),
    onStateChanged: (callback) => subscribe("p2p:stateChanged", callback),
    onReconnecting: (callback) => subscribe("p2p:reconnecting", callback),
  },

  activity: {
    list: () => ipcRenderer.invoke("activity:list"),
    onCreated: (callback) => subscribe("activity:created", callback),
  },

  fileWatcher: {
    start: (payload) => ipcRenderer.invoke("fileWatcher:start", payload),
    stop: () => ipcRenderer.invoke("fileWatcher:stop"),
    status: () => ipcRenderer.invoke("fileWatcher:status"),
    triggerSync: () => ipcRenderer.invoke("fileWatcher:triggerSync"),
    pushToMain: (payload) => ipcRenderer.invoke("fileWatcher:pushToMain", payload),
    onChanged: (callback) => subscribe("fileWatcher:changed", callback),
    onStatus: (callback) => subscribe("fileWatcher:status", callback),
    onSyncStart: (callback) => subscribe("fileWatcher:syncStart", callback),
    onSyncComplete: (callback) => subscribe("fileWatcher:syncComplete", callback),
    onPullComplete: (callback) => subscribe("fileWatcher:pullComplete", callback),
    onPeerSync: (callback) => subscribe("fileWatcher:peerSync", callback),
  },

  openDirectory: () => ipcRenderer.invoke("system:openDirectory"),
  openExternal: (url) => ipcRenderer.invoke("system:openExternal", url),
  runCommand: (command, cwd) => ipcRenderer.invoke("process:run", { command, cwd }),
  onTerminalOutput: (callback) => subscribe("process:output", (payload) => callback(payload.chunk)),
  platform: process.platform,
});
